export const baseUrl = 'http://localhost:3001/api/v1'

export const authToken = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiYWJkdWxsYWg5OTlAZ21haWwuY29tIiwidXNlcm5hbWUiOiJhYmR1bGxhaCIsImlhdCI6MTcwMTY3OTcxOSwiZXhwIjoxNzAxNzY2MTE5fQ.uFwnbIxbc6_JPaYWTjGIU-9b8nL0-MOQKI1JLFHhqsk'